# For documentation on how to configure this file,
# see https://diesel.rs/guides/configuring-diesel-cli

[print_schema]
file = "src/schema.rs"
custom_type_derives = ["diesel::query_builder::QueryId", "Clone"]

[migrations_directory]
dir = "/mnt/sdc1/Estudo/Programaçao/Projects/CodeMiner/rust/hackathon_2024/witbarden/migrations"
